apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
    role: master
    tier: backend
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: backend
    role: master
    tier: backend
