apiVersion: v1
kind: Service
metadata:
  name: jaeger-master
  labels:
    app: jaeger
    role: master
    tier: backend
spec:
  type: NodePort
  ports:
  - port: 6831
    targetPort: 6831
  selector:
    app: jaeger
    role: master
    tier: backend
