apiVersion: v1
kind: Service
metadata:
  name: jaeger-master
  labels:
    app: jaeger
    role: master
    tier: backend
spec:
  type: LoadBalancer
  ports:
  - port: 16686
    targetPort: 16686
  selector:
    app: jaeger
    role: master
    tier: backend
