apiVersion: v1
kind: Service
metadata:
  name: jaeger-master
  labels:
    app: jaeger
    role: master
    tier: backend
spec:
  type: LoadBalancer
  ports:
  - name: ui
    port: 16686
    targetPort: 16686
  - name: collector
    port: 6831
    targetPort: 6831
  selector:
    app: jaeger
    role: master
    tier: backend
